### ISSUE TITLE
Not able to choose which spells to show or hide

### ISSUE THREAD

**Issue by Beenhouwer** [casualshammy/NameplateCooldowns#121]
This addon would be so much better if I could just add or remove all the spells I want to show on the nameplates.  Now there is just no possible way for me to change any of the default spells that are showing. 

Can you please make a drop down menu with all the classes with their respected spells so we can just hand pick the ones we want to show? I believe an earlier version of this addon had this feature, but now its gone.. This would make this one of the best pvp addons in the game if the spells were just made customisable.

Thanks in advance!

**Comment by casualshammy** [comment]
Hello!
> This addon would be so much better if I could just add or remove all the spells I want to show on the nameplates

It would be the best solution, but there is a big problem: updating spells. I have to provide a build-in list of spells because many of players don't want to dig in wowhead in search of spells, spells modifiers and so on. The question is: how to update cooldown info if users want to have an ability to change cooldown info? Currently, if user sets custom cooldown duration for any spell, it persists during addon updates. This options is like "hey, so you want to manage cooldown of this spell by youself? okay, but now it is YOUR responsibility to maintain it". 
Back to your request. Let's say you have deleted all spells you don't like and added another spells you want to track. Okay, it will work. Until the next update :) 
1. New usable talent was added. Should I add it to your list by default? But you deleted a lot of spells, looks like you know what to do. In the other way, you will miss the important save of burst cooldown... What is the best solution? I can ensure you that here on github will be a couple of issue reports demanding "add anyways" and "not add" behaviours.
2. You have added spell that is not in the build-in list. Okay, next update came and now it IS in the build-in list, BUT cooldown is different. What should I do?

BTW, you are right, there was the ability to add and delete spells, but users were confused by default behavior of addon during updates. I have spent quite a lot time to implement custom spells, but I just don't know how to make it work, sorry.

**Comment by Beenhouwer** [comment]
Thanks for the quick response!

But there should be a way to select the spells from a list right? Because right now I have a button that says “click here to select spells” but it doesnt work, nothing comes up. The button is also not grey but red so I think maybe it is bugged or something?
anyways really appreciate the work you are doing, this addon can be so much better then omnibar in my opinion!

**Comment by casualshammy** [comment]
Hrm, looks like your settings file is corrupted, or maybe I did something wrong. Could you please try this:
1. Create new profile and switch to it
2. Reload UI (this is important)
3. Check if the spell list is still empty
