### ISSUE TITLE
Show Unused cooldowns

### ISSUE THREAD

**Issue by mevin19** [casualshammy/NameplateCooldowns#20]
Hi, I really like this addon i prefer it over omnibar so i don't tunnel vision looking down but instead look at the game itself. My problem is that Nameplatecooldowns does not have an option to show Unused cooldowns, this is a feature that i would really like to see it helps me a lot more to predict what the enemy player is about to do. Please make a Unused cooldowns feature like omnibar has. 

Thank you in advance

**Comment by casualshammy** [comment]
Unfortunately, NameplateCooldowns doesn't know anything about classes and specs, because it goes against another feature I was asked some time ago - ability to add spells in-game. As result, this addon just don't know what inactive cooldown it should show.
I can make it another way: if a foe has used spell that you have checked for tracking, it will be shown as 'inactive cooldown' above this foe's nameplate.

**Comment by mevin19** [comment]
Ah, Yeah that could do the trick! I Would very much appricate that, I know it's probably not a big priority but in the future i would really like to see what you just mentioned.

Thanks!

**Comment by casualshammy** [comment]
I will appreciate if you'll find spare time to try out the latest beta (you can install it via Twitch client or [directly](https://www.curseforge.com/wow/addons/nameplatecooldowns/download/3052190))

**Comment by mevin19** [comment]
Oh wow! the option is working exactly as I had hoped for, this is a huge upgrade for me thank you a lot for getting this out this quick!
