### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by FelipeOrtuzarSawred** [casualshammy/NameplateCooldowns#26]
**Describe the bug**
Hello,

I have a problem with one of my characters, specifically the Priest, which does not differentiate the size of the target icon. Both characters share the same profile.

Regards

**Screenshots**
Attached image
![WoWScrnShot_091120_233728](https://user-images.githubusercontent.com/64238286/92985402-7db58880-f488-11ea-86eb-99d16ce911eb.jpg)
![WoWScrnShot_091120_234132](https://user-images.githubusercontent.com/64238286/92985403-7ee6b580-f488-11ea-9fc9-fe04b2ff1a76.jpg)

**Comment by casualshammy** [comment]
Hello.
I guess you have checked `Always display CD icons at full opacity` option on the first character. This option has side effects on scaling. I'll implement a separate options for opacity and scaling in next release.

**Comment by FelipeOrtuzarSawred** [comment]
I have the "x" option disabled in all the characters because for me it is visually better to see the larger icons in the selected target. I attach images.
![WoWScrnShot_091220_093129](https://user-images.githubusercontent.com/64238286/92995592-3f958480-f4db-11ea-9eac-1a167dfd8f43.jpg)
![WoWScrnShot_091220_093235](https://user-images.githubusercontent.com/64238286/92995595-40c6b180-f4db-11ea-8f91-3626b141e26a.jpg)

**Comment by casualshammy** [comment]
TBH I don't know how to get this behavior just by my addon. Anyway, I'll rework opacity and scaling feature soon. Will see if this helps.

**Comment by casualshammy** [comment]
I will appreciate if you'll find spare time to try out the latest beta (you can install it via Twitch client or download [directly](https://www.curseforge.com/wow/addons/nameplatecooldowns/download/3056993)). I don't know if your issue is fixed in this beta (because nameplates can be modified by a number of addons), but try to check/uncheck this options:
![Picture](https://user-images.githubusercontent.com/4965168/93085820-149f6200-f68e-11ea-93a5-379aa22f97d0.png)

**Comment by FelipeOrtuzarSawred** [comment]
My friend, finally the problem was with Blizzard's cvar settings.

I appreciate your work.

Regards
