### ISSUE TITLE
Update for Shadowlands Pre-Patch (9.0.1) needed

### ISSUE THREAD

**Issue by ikrug** [casualshammy/NameplateCooldowns#31]
Die to lvl squish, ability changes (some back, some reworked, some removed, some available after prepatch in 50+ lvl) current version isn't work properly.

Please update it if possible.

Thank you!

**Comment by casualshammy** [comment]
Hello.
I'll update all spells soon, but... Blizzard makes it **really** hard to calculate the real cooldown of spells. Shadowlands made it even worse. All this anima, covenants, talents of followers, procs, procs of procs, etc. So, at least half of the spells in NC's list have incorrect cooldown values.

**Comment by ikrug** [comment]
Thank you!
I understand that BfA and SL systems a pain for any developer =/

**Comment by TeddeCodesAddons** [comment]
@casualshammy (NameplateCooldowns) BTW found a way to fix it - If you need a way to get an easy fix for the AddOn, I did this to mine:
1. Look for any files that include CreateFrame() in them
2. Add a script at the top of the file.
The script is: (All on one line to avoid taking extra bytes)
`local t=BackdropTemplateMixin and"BackdropTemplate"local cf=CreateFrame local function CreateFrame(a1,a2,a3,inh,...)if inh then inh=inh..","..t else inh=t end return cf(a1,a2,a3,inh,...)end`

I use this addon on a day-to-day basis, so ty for making it! Hope this helps!

Also, some of the shadowlands spells need to be shown on them. (I think you were already notified) but it still shows me their interrupts, which is why I use it.

**Comment by TeddeCodesAddons** [comment]
again, i think i noticed something - the github project includes the new "BackdropTemplate" statement, but i think the curse forge version is not up to date, i just noticed that...

**Comment by casualshammy** [comment]
@TeddeCodesAddons I've just downloaded the latest release from curseforge (80300.13-release). There are not problems with `BackdropTemplate`

**Comment by casualshammy** [comment]
I've uploaded a new release (90001.0-release). It contains updated spell cooldowns (except anima and covenants - they will be added after Shadowlands release).
@TeddeCodesAddons This `BackdropTemplate`-related issues are caused by old version of GUI library. I wish I had noticed it earlier... Anyway, thank you for reporting.

**Comment by casualshammy** [comment]
TODO: add covenants spells.
