### ISSUE TITLE
addon didnt work

### ISSUE THREAD

**Issue by badparadise** [casualshammy/NameplateCooldowns#35]
Hi! the addon didnt show any icons above the plates. Im testing everything but nothing really matters, just didnt work, im speaking with another people who have the addons and for they didnt work too. (spanish version).

neither if I put "/nc" on the chat didnt work too, but i have the panel on my interface and i can modify whatever i want but with no modifiers on the game.

think thats happens with the patch 9.0.1 (just maybe) because i dont have any issue more than this one.

should i change the lenguaje of something or will fix anything? thank u

**Comment by casualshammy** [comment]
Hi.
What version are you using?

**Comment by badparadise** [comment]
https://gyazo.com/4f2034cf13b1df67568cb6254c87cff1

**Comment by casualshammy** [comment]
Hmm, I have just tested addon on new character, and it works well. `esES` locale also doesn't contain fatal errors. I need more information to fix this issue. For example, lua error log would be great.
Also, try to disable all other addons. I know it's boring and inconvenient, but that's all I can recommend without lua error report.

**Comment by badparadise** [comment]
how can i take the lua error report of this?

**Comment by casualshammy** [comment]
Log-in your character. Enter `/console scriptErrors 1` in your chat. Do battleground or duel (**not rated pvp**). If there is a problem, window with error description will appear. Copy this description here.

**Comment by badparadise** [comment]
Message: ...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:113: NameplateCooldowns has already been added to the Blizzard Options Window with the given path
Time: Tue Nov  3 17:57:43 2020
Count: 1
Stack: ...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:113: NameplateCooldowns has already been added to the Blizzard Options Window with the given path
[string "@Interface\AddOns\RCLootCouncil\Core\ErrorHandler.lua"]:146: in function <Interface\AddOns\RCLootCouncil\Core\ErrorHandler.lua:144>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\GatherMate2\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:2013: in function `AddToBlizOptions'
[string "@Interface\AddOns\NameplateCooldowns\NameplateCooldowns.lua"]:113: in function <...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:94>
[string "@Interface\AddOns\NameplateCooldowns\NameplateCooldowns.lua"]:187: in function <...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:138>
[string "@Interface\AddOns\NameplateCooldowns\NameplateCooldowns.lua"]:232: in function <...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:230>
[string "@Interface\AddOns\NameplateCooldowns\NameplateCooldowns.lua"]:2626: in function `?'
[string "@Interface\AddOns\NameplateCooldowns\NameplateCooldowns.lua"]:2571: in function <...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:2571>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Core\ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Core\ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Core\ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Core\ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Core\ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Core\ErrorHandler.lua:77
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Core\ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Core\ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355

**Comment by casualshammy** [comment]
It's the only error you got? I ask this because there is something that prevents NameplateCooldowns from load properly.

**Comment by badparadise** [comment]
i have this one

Message: ...l\Libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:212: attempt to call method 'SetBackdrop' (a nil value)
Time: Tue Nov  3 18:26:13 2020
Count: 1
Stack: ...l\Libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:212: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\RCLootCouncil\Libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua"]:212: in function `CreateDropDownList'
[string "@Interface\AddOns\RCLootCouncil\Libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua"]:390: in main chunk

Locals: name = "MSA_DropDownList1"
parent = nil
DropDownList = MSA_DropDownList1 {
 0 = <userdata>
}
frame1 = MSA_DropDownList1Backdrop {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = MSA_DropDownList1Backdrop {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background-Dark"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined =[C]:-1
 ERR_OUT_OF_CHI = "No tienes suficiente chi"
 DH_HAVOC_CORE_ABILITY_2 = "Ataque cuerpo a cuerpo fuerte que consume furia. Cuando asesta un golpe crítico, devuelve algo de furia."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Colorear el nombre de unidades."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 741
 SPELL_FAILED_CUSTOM_ERROR_71 = "Este fiestero quiere bailar contigo."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 400
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "No se pueden crear más enlaces de invitación para esta comunidad."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "No puedes comerciar con bolsas equipadas."
 PVP_RANK_6_1 = "Cabo"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 DetailsWindowOptionsBarTextEditorEntryNumberLines = DetailsWindowOptionsBarTextEditorEntryNumberLines {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Los atajos de los botones de acción responderán al pulsar una tecla y no al soltarla."
 BINDING_NAME_NAMEPLATES = "Placas de nombre: ver enemigos"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Salud"
 MAIL_LETTER_TOOLTIP = "Haz clic para hacer una copia
permanente de esta carta."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface\FrameXML\UnitFrame.lua:782
 PaperDollTitlesPaneButton10BgTop = PaperDollTitlesPaneButton10BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Sala de Puño Negro"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2379
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "No es posible susurrar a '%s'. Puede que el servicio de Blizzard no esté disponible."
 AutoCompleteEditBox_OnKeyDown = <function> defined @Interface\FrameXML\AutoComplete.lua:366
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTelepor


and one more about RCLootCouncil, should i try to desactivate the RCLoot?

**Comment by casualshammy** [comment]
I don't think it will actually help, but the problem is strange enough, so please give it a try.

**Comment by badparadise** [comment]
definitely not problem about RCLootCouncil, have now only 1 error lua and it is:


Message: ...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:214: invalid option in `format'
Time: Tue Nov  3 18:37:39 2020
Count: 1
Stack: ...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:214: invalid option in `format'
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\NameplateCooldowns\NameplateCooldowns.lua"]:214: in function <...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:194>
[string "@Interface\AddOns\NameplateCooldowns\NameplateCooldowns.lua"]:233: in function <...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:230>
[string "@Interface\AddOns\NameplateCooldowns\NameplateCooldowns.lua"]:2626: in function `?'
[string "@Interface\AddOns\NameplateCooldowns\NameplateCooldowns.lua"]:2571: in function <...ace\AddOns\NameplateCooldowns\NameplateCooldowns.lua:2571>

Locals:

**Comment by casualshammy** [comment]
Ah, got it. There is a problem in Spanish localization. Please try this build
[NameplateCooldowns0.zip](https://github.com/casualshammy/NameplateCooldowns/files/5483093/NameplateCooldowns0.zip)

**Comment by badparadise** [comment]
https://gyazo.com/b19412e12e33bc202e4f8dcab0f36d05

that means something like "some changes about ur habilities, wanna try if there are updates? yes, no."

what should i choose

**Comment by casualshammy** [comment]
I have updated cooldown values for Shadowlands. Normally you should answer "yes"

**Comment by casualshammy** [comment]
Please report if problem is solved (or not). If it's OK, I'll upload fixed build to curseforge then.

**Comment by badparadise** [comment]
https://gyazo.com/9a96f04930d2a44c16cb46b93eb42806

it solved. thank you boss!

**Comment by casualshammy** [comment]
Thank you for patience!

**Comment by Agrecan** [comment]
> Ah, lo tengo. Hay un problema en la localización al español. Prueba esta compilación
> [NameplateCooldowns0.zip](https://github.com/casualshammy/NameplateCooldowns/files/5483093/NameplateCooldowns0.zip)

Hola, con esa compilación me funcionó, puedo ver los iconos, pero me arroja error todo el rato.

Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
Time: Thu Nov  5 18:12:56 2020
Count: 1
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
[string "=[C]"]: in function `GetRaidTargetIndex'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:216: in function `OnRaidTargetUpdate'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:122: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = nil
Más información sobre este texto de origenPara obtener más información sobre la traducción, se necesita el texto de origen
Enviar comentarios
Paneles laterales

**Comment by Agrecan** [comment]
> Hmm, acabo de probar el complemento en un nuevo personaje y funciona bien. `esES`locale tampoco contiene errores fatales. Necesito más información para solucionar este problema. Por ejemplo, el registro de errores de lua sería genial.
> Además, intente deshabilitar todos los demás complementos. Sé que es aburrido e inconveniente, pero eso es todo lo que puedo recomendar sin el informe de error de lua.

Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
Time: Thu Nov  5 18:17:32 2020
Count: 3
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
[string "=[C]"]: in function `GetLeft'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:470: in function `GetPreferredInsets'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:166: in function `UpdateInsetsForType'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:150: in function `ApplyFrameOptions'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:116: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = <unnamed> {
 otherHealPrediction = <unnamed> {
 }
 b = 0
 myHealAbsorbLeftShadow = <unnamed> {
 }
 border = <unnamed> {
 }
 background = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 barTexture = <unnamed> {
 }
 0 = <userdata>
 r = 0
 totalAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 g = 1
 totalAbsorbOverlay = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
}
Message: Interface\FrameXML\AuraUtil.lua:58: Usage: local continuationToken, slot1, slot2, ... = UnitAuraSlots("unit" [, "filter"][, maxSlots][, continuationToken])
Time: Thu Nov  5 18:18:00 2020
Count: 62
Stack: Interface\FrameXML\AuraUtil.lua:58: Usage: local continuationToken, slot1, slot2, ... = UnitAuraSlots("unit" [, "filter"][, maxSlots][, continuationToken])
[string "=[C]"]: in function `UnitAuraSlots'
[string "@Interface\FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:597: in function `UpdateBuffs'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:209: in function `OnUnitAuraUpdate'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:65: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = nil
(*temporary) = "HARMFUL|INCLUDE_NAME_PLATE_ONLY"
(*temporary) = 32
(*temporary) = nil
Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
Time: Thu Nov  5 18:17:34 2020
Count: 2
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
[string "=[C]"]: in function `GetRaidTargetIndex'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:216: in function `OnRaidTargetUpdate'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:122: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = nil

**Comment by casualshammy** [comment]
@Agrecan Please don't post comments in closed tickets. Why do you think your errors are related to NameplateCooldowns? There are not references to my addon in your logs. My addon just doesn't use functions that caused errors.

**Comment by Agrecan** [comment]
> @Agrecan Por favor, no publique comentarios en boletos cerrados. ¿Por qué cree que sus errores están relacionados con NameplateCooldowns? No hay referencias a mi complemento en sus registros. Mi complemento simplemente no usa funciones que causaron errores.

If I activate NameplateCooldowns, it will get errors, if I deactivate it, it will not get errors.
