### ISSUE TITLE
covenant abilities missing

### ISSUE THREAD

**Issue by Resune** [casualshammy/NameplateCooldowns#58]
Now that you're not able to add spells to this addon, a lot of covenant abilities are missing, some are here and some are gone.

I'd also like to suggest the ability to modify cooldowns on existing spells

**Comment by casualshammy** [comment]
I'm not happy with this desicion, but I had to remove ability to add/edit cooldowns. Why? Because maintaining lists of default spells **and** user-defined spells **and** modified default spells is too difficult to implement without distractions for users. 

All main covenant abilities were added recently. Is there something I've missed?

**Comment by cameronlb** [comment]
Just came here to see if its possible to added user spells in the lua files, "kleptomania id:198100" is missing for mage pvp talent.

**Comment by Resune** [comment]
Divine Toll is a massive ability to forget, that's my biggest concern with missing abilities, I'd like to see soulshape and chain harvest as well.

**Comment by casualshammy** [comment]
@cameronlb Kleptomania is passive talent that increases cooldown of spell. NameplateCooldowns cannot determine (in reliable way) that player have his talent.
@Resune Added Divine Toll and Chain Harvest. I'll add Soulshape later.
