### ISSUE TITLE
No CD timer when "show inactive cooldowns" + "inverse logic"

### ISSUE THREAD

**Issue by Rackelhardt** [casualshammy/NameplateCooldowns#87]
I want to see the icon when its ready to use. 
So i need to enable "show inactive cooldowns"

But then the item is coloured when on CD and desaturated when ready (imho it should be the opposite)
So i activate "inverse logic" now its coloured when ready and desaturated when on CD, great.
But now it has no timer anymore :(

My perfect option would be a transparent/dimmed/desaturated (whatever) item with CD timer (and maybe even swirl) when its on CD and a coloured (normal) icon when its ready...
Thats how it is in your own action bar and thats how it should be in this addon (imho).

**Comment by casualshammy** [comment]
> Thats how it is in your own action bar and thats how it should be in this addon (imho).

No, it shouldn't. I'm not trying to offence, just a fact: this addon from the very begin in 2013 was about `enemy cooldowns`, not about `abilities enemy can use right now`. `Show inactive cooldowns` and `Inverse logic` options were made just for fun, I didn't imagine that they will be popular options. I - as this addon developer - can't make this features work properly and reliable because of the nature of addon API (and very 'fun' things like dynamic, not-fixed cooldowns).
But I've implemented your request and will push it in release this weekend.

**Comment by Rackelhardt** [comment]
Thank you for your answer.
I understand you.
The thing is: I just run a few CDs below my nameplates and sometimes you
can just forget it if you can't see them.
For example if I see a priest close to me with [Fear] ready, I will more
likely place my Tremor Totem.
If I don't see that Icon (ready to use), I might not think about it in a
stressful situation.

Thank you for releasing it <3 <3 <3

Btw. After I read my request again, it sounded a bit harsh. That wasn't my
intention, sry.

Am Do., 9. Sept. 2021 um 20:48 Uhr schrieb casualshammy <
***@***.***>:

**Comment by casualshammy** [comment]
Implemented in `90100.10-release`.
